name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Checkout destination repository
        uses: actions/checkout@v3
        with:
          repository: tsj7ww/tsj7ww.github.io
          token: ${{ secrets.PAT_TOKEN }}
          path: dest-repo
      
      - name: Copy static files
        run: |
          find ./dest-repo -mindepth 1 ! -path './dest-repo/.git*' ! -path './dest-repo/.github*' -exec rm -rf {} +
          cp -r static/* dest-repo/
          
      - name: Commit and push changes
        run: |
          cd dest-repo
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy static files from website repository" || echo "No changes to commit"
          git push